# app
FROM node:alpine as dev-stage
WORKDIR /app

# documentation
FROM node:alpine as docs-dev-stage
RUN yarn global add vuepress
WORKDIR /app

# mock server
FROM node:alpine as mock-server
RUN npm install -g nodemon
WORKDIR /data